services:
  app:
    image: node:22-alpine
    container_name: ngobrol_yuk_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - CHOKIDAR_INTERVAL=100
